name: Busybox Print

on:
  push:
    branches:
      - master1

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Run BusyBox to print message
        uses: docker://busybox:latest
        with:
          args: echo "Hello from BusyBox in GitHub Actions!"
